name: Build App for Release

on:
  release:
    types: [prereleased]

permissions: write-all

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install frontend dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./frontend

      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend

      - name: Package and Build the Electron app
        run: |
          npm run make
        working-directory: ./backend

      - name: Archive the build (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p distributables/deb distributables/rpm
          cp ./backend/out/make/deb/**/*.deb distributables/deb/quick-finder-amd64.deb
          cp ./backend/out/make/rpm/**/*.rpm distributables/rpm/quick-finder-x86_64.rpm
          cd distributables
          zip -r quickfinder-linux.zip *
          cd ..

      - name: Archive the build (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir distributables
          cd ./backend/out/make
          powershell Compress-Archive -Path * -DestinationPath ../../../distributables/quickfinder-windows.zip
          cd ../../..

      - name: Collect built distributables (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          mkdir distributables
          cd ./backend/out/make
          cp *.dmg ../../../distributables/QuickFinder.dmg
          cd ../../..

      - name: Upload the build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: distributables/*

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./artifacts

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset (Ubuntu - deb)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./artifacts/build-ubuntu-latest/deb/quick-finder-amd64.deb
          asset_name: quick-finder-amd64.deb
          asset_content_type: application/vnd.debian.binary-package

      - name: Upload Release Asset (Ubuntu - rpm)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./artifacts/build-ubuntu-latest/rpm/quick-finder-x86_64.rpm
          asset_name: quick-finder-x86_64.rpm
          asset_content_type: application/x-rpm

      - name: Upload Release Asset (macOS)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./artifacts/build-macos-latest/QuickFinder.dmg
          asset_name: quickfinder-macos.dmg
          asset_content_type: application/octet-stream

      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            build-ubuntu-latest
            build-macos-latest
